### ISSUE TITLE
Send BCC: (Blind carbon copy)

### ISSUE THREAD

**Issue by ppjuarez** [Novadge/novamail#5]
I'm trying to send emails with blind carbon copy, so the recipient can't see other recipient's email address, but I can't find any option to do this, not in the documentation nor the code.

**Comment by Omasiri** [comment]
Thanks for your feedback. 
We now have method like  `boolean sendEmail(String hostname, String username, String password, String from, String to, String cc, String bcc,String subject, String body,Map hostProps)`
